name: crypto_dart
description: a dart libary that tries to implement crypto-js like functionality.
version: 1.0.3+1
repository: https://github.com/Noobware1/crypto_dart
topics:
  - crypto
  - cryptography

environment:
  sdk: ^3.0.6

dependencies:
  pointycastle: ^3.7.3
  convert: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
